// Auto-generated by scripts/generate-service-worker.mjs — do not edit by hand.
// Version: roadbook-v20260830-1719
const VERSION = "roadbook-v20260830-1719";
const ASSET_CACHE = "roadbook-assets-" + VERSION;
const TILE_CACHE = "roadbook-tiles-" + VERSION;
const TILE_HOST_RE = new RegExp(/^([a-c])\.(?:tile|ssl)\.openstreetmap\.org$/) || new RegExp(/^webrd0[1-4]\.is\.autonavi\.com$/);

// Everything precached/cached is expressed relative to the folder holding this
// worker, so the build is portable across deployment roots.
const BASE = new URL("./", new URL("sw.js", self.location.href)).href;
const OFFLINE_URL = new URL("offline.html", BASE).href;

const PRECACHE_URLS = [
  "assets/desktop-CZxoqjPc.js",
  "assets/icons-B1lzsNUh.js",
  "assets/map-vendor-CIGW-MKW.css",
  "assets/map-vendor-Dk73KsM1.js",
  "assets/mobile-BAWkvOUd.css",
  "assets/mobile-YiAGp86l.js",
  "assets/react-vendor-BVAQ-h3e.js",
  "assets/styles-DEoo5Zlr.js",
  "assets/styles-DvnvGa-d.css",
  "desktop.html",
  "icons/apple-touch-icon.png",
  "icons/favicon-32.png",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/maskable-512.png",
  "index.html",
  "manifest.webmanifest",
  "mobile.html",
  "offline.html"
].map((entry) => new URL(entry, BASE).href);

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(ASSET_CACHE)
      .then((cache) => cache.addAll(PRECACHE_URLS))
      .catch(() => undefined)
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      const keys = await caches.keys();
      await Promise.all(
        keys.filter((name) => !name.endsWith(VERSION)).map((name) => caches.delete(name)),
      );
      if ("navigationPreload" in self.registration) {
        try {
          await self.registration.navigationPreload.enable();
        } catch {
          /* older browsers without navigation preload */
        }
      }
      await self.clients.claim();
    })(),
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;

  let url;
  try {
    url = new URL(request.url);
  } catch {
    return;
  }

  // OSM raster tiles: stale-while-revalidate so the user can still see maps
  // they have already panned through even with no network.
  if (
    url.protocol === "https:" &&
    TILE_HOST_RE.test(url.hostname) &&
    url.pathname.startsWith("/")
  ) {
    event.respondWith(staleWhileRevalidate(request, TILE_CACHE));
    return;
  }

  if (url.origin !== self.location.origin) return;

  // HTML navigations: network-first so users get the latest deployment when
  // online, with a cached copy and finally the offline page as fallbacks.
  if (request.mode === "navigate" || request.headers.get("accept")?.includes("text/html")) {
    event.respondWith(navigationStrategy(request));
    return;
  }

  // Hashed static assets: cache-first with a background refresh.
  event.respondWith(cacheFirstWithRefresh(request));
});

async function navigationStrategy(request) {
  const cache = await caches.open(ASSET_CACHE);
  try {
    const response = await fetch(request);
    if (response && response.ok) cache.put(request, response.clone());
    return response;
  } catch {
    const cached = await cache.match(request);
    if (cached) return cached;
    const offline = await cache.match(OFFLINE_URL);
    if (offline) return offline;
    return new Response("Offline", { status: 503, statusText: "Offline" });
  }
}

async function cacheFirstWithRefresh(request) {
  const cache = await caches.open(ASSET_CACHE);
  const cached = await cache.match(request);
  const refresh = fetch(request)
    .then((response) => {
      if (response && response.ok) cache.put(request, response.clone());
      return response;
    })
    .catch(() => null);
  if (cached) {
    refresh.catch(() => undefined);
    return cached;
  }
  const fresh = await refresh;
  if (fresh) return fresh;
  return new Response("", { status: 504, statusText: "Offline" });
}

async function staleWhileRevalidate(request, cacheName) {
  const cache = await caches.open(cacheName);
  const cached = await cache.match(request);
  const network = fetch(request)
    .then((response) => {
      if (response && (response.ok || response.type === "opaque")) {
        cache.put(request, response.clone()).then(() => trimCache(cacheName, 600));
      }
      return response;
    })
    .catch(() => cached || new Response("", { status: 504, statusText: "Offline" }));
  return cached || network;
}

async function trimCache(cacheName, maxEntries) {
  try {
    const cache = await caches.open(cacheName);
    const keys = await cache.keys();
    if (keys.length <= maxEntries) return;
    const excess = keys.length - maxEntries;
    for (let i = 0; i < excess; i += 1) {
      await cache.delete(keys[i]);
    }
  } catch {
    /* nothing actionable */
  }
}
